"""add account type and category to tenants

Revision ID: 001d373aed2e
Revises: 6a809716a795
Create Date: 2026-04-09 10:39:53.530628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001d373aed2e'
down_revision = '6a809716a795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.String(length=20), server_default='business', nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('account_type')

    # ### end Alembic commands ###
