"""add recipient_id to messages

Revision ID: 7d975c8e8d7e
Revises: 91aba36146c6
Create Date: 2026-04-08 23:11:52.803899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d975c8e8d7e'
down_revision = '91aba36146c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_messages_recipient_id', 'users', ['recipient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_recipient_id', type_='foreignkey')
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###
