"""add tenant_settings

Revision ID: bdfbf11d9773
Revises: 7d975c8e8d7e
Create Date: 2026-04-08 23:51:36.370217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdfbf11d9773'
down_revision = '7d975c8e8d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('restock_platforms', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('recipient_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('recipient_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    op.drop_table('tenant_settings')
    # ### end Alembic commands ###
