"""add allowed_categories to users

Revision ID: e5895f7dc055
Revises: caf5cc3e8d58
Create Date: 2026-04-26 16:23:16.522088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5895f7dc055'
down_revision = 'caf5cc3e8d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_categories', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('allowed_categories')

    # ### end Alembic commands ###
